### ISSUE TITLE
Nudenet Classifier Error

### ISSUE THREAD

**Issue by ssssssman** [ShamHyper/MultiAI#1]
from nudenet import NudeClassifier ImportError: cannot import name 'NudeClassifier' from 'nudenet' (unknown location)

I running installer.bat first. Python 3.9

**Comment by ShamHyper** [comment]
Oh, I'll check this

**Comment by ShamHyper** [comment]
#1

**Comment by ShamHyper** [comment]
Fixed in 0.6.0 - https://github.com/ShamHyper/MultiAI/commit/62d182f09783b83acafc910af30870681b5e14e8
